In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)

In [4]:
x_ones = torch.ones_like(x_np)
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand_int = torch.rand_like(x_rand, dtype = torch.float)
print(f"{x_ones}\n{x_rand}\n{x_rand_int}")

tensor([[1, 1],
        [1, 1]])
tensor([[0.4955, 0.6735],
        [0.5062, 0.0595]])
tensor([[0.7336, 0.3118],
        [0.9009, 0.8304]])


In [5]:
shape = (2,9,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("{}\n{}\n{}".format(rand_tensor, ones_tensor, zeros_tensor))

tensor([[0.3743, 0.8084, 0.4847, 0.1730, 0.9957, 0.9243, 0.1943, 0.1691, 0.3453],
        [0.4354, 0.3723, 0.7910, 0.6530, 0.0440, 0.1279, 0.0872, 0.7327, 0.6862]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [6]:
print("{} {} {}".format(rand_tensor.shape, rand_tensor.dtype, rand_tensor.device))

torch.Size([2, 9]) torch.float32 cpu


In [7]:
tensor = torch.ones(2,4)
print(tensor)
print(f"row1 : {tensor[0]}")
print(f"col1 : {tensor[:, 0]}")

tensor[:, -1] = 0

print(f"""
      col_last : {tensor[:, -1]}
      col_last_alt : {tensor[..., -1]}
      
      notice : tensor[..., -1] = tensor[:,:,:,~~~생략~~~,-1]
""")
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
row1 : tensor([1., 1., 1., 1.])
col1 : tensor([1., 1.])

      col_last : tensor([0., 0.])
      col_last_alt : tensor([0., 0.])
      
      notice : tensor[..., -1] = tensor[:,:,:,~~~생략~~~,-1]

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1_x= torch.cat([tensor, tensor, tensor], dim = 0)
print(f"\n{t1} \n\n {t1_x} \n")

t2 = torch.stack([tensor, tensor, tensor], dim = 2)
# t2 = torch.stack([tensor, tensor, tensor], dim = 1 #or 0) << 차이가 없음 
print(t2)

print(f"\n{t2[:,:,-1]} \n\n {t2[..., -1]}") #***


tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]]) 

 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]]])

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

 tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.]])
